name: Modularis Publish

on:
  push:
    paths: ./api/modularis
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api/modularis

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ secrets.MODULARIS_IMAGE_NAME }}
          COMMIT_SHA=${{ github.sha }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$COMMIT_SHA \
            --build-arg ConnectionStrings__SqlServer="${{ secrets.MODULARIS_SQL_SERVER_CONNECTION_STRING }}" \
            --build-arg Datadog__ApiKey="${{ secrets.MODULARIS_DATADOG_API_KEY }}" \
            --build-arg Datadog__Service="${{ secrets.MODULARIS_DATADOG_SERVICE }}" \
            --build-arg Datadog__Host="${{ secrets.DATADOG_HOST }}" \
            --build-arg Datadog__Url="${{ secrets.DATADOG_URL }}" .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$COMMIT_SHA
