name: Modularis Publish

on:
  push:
    paths: ./api/modularis
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api/modularis

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.MODULARIS_IMAGE_NAME }}:latest \
            --build-arg ConnectionStrings__SqlServer="${{ secrets.MODULARIS_SQL_SERVER_CONNECTION_STRING }}" .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.MODULARIS_IMAGE_NAME }}:latest
