name: Web Publish

on:
  push:
    paths:
      - './web/**'
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Web Publish
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/abreu-dev_nexus_web
          COMMIT_SHA=${{ github.sha }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$COMMIT_SHA .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$COMMIT_SHA
